# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer', '0002_author_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='belt_reviewer.User'),
            preserve_default=False,
        ),
    ]
